name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Permissions
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" | sed 's/\\n/\n/g' > key.pem
          chmod 600 key.pem

      - name: Sync Backend to Droplet
        env:
          SSH_HOST: huytran3.workspace.opstech.org
          SSH_USER: root
        run: |
          rsync -avz --exclude='node_modules' --exclude='.git' --exclude='.github' \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ $SSH_USER@$SSH_HOST:/var/www/backend
          ssh -i key.pem $SSH_USER@$SSH_HOST "cd /var/www/backend && npm install && pm2 restart backend"

      - name: Sync Admin Frontend to Droplet
        env:
          SSH_HOST: huytran3.workspace.opstech.org
          SSH_USER: root
        run: |
          rsync -avz --exclude='node_modules' --exclude='.git' --exclude='.github' \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./admin-frontend/ $SSH_USER@$SSH_HOST:/var/www/admin-frontend
          ssh -i key.pem $SSH_USER@$SSH_HOST "cd /var/www/admin-frontend && npm install && npm run build && pm2 restart admin-frontend"

      - name: Sync Admin Frontend to Droplet
        env:
          SSH_HOST: huytran3.workspace.opstech.org
          SSH_USER: root
        run: |
          rsync -avz --exclude='node_modules' --exclude='.git' --exclude='.github' \
          -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./admin-frontend/ $SSH_USER@$SSH_HOST:/var/www/admin-frontend
          ssh -i key.pem $SSH_USER@$SSH_HOST "cd /var/www/admin-frontend && npm install && npm run build && pm2 restart admin-frontend"

# Deploy test
